# Generated by Django 6.0.1 on 2026-01-21 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('glb_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='I3DMTileset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên tileset')),
                ('count', models.IntegerField(verbose_name='Số instances')),
                ('min_lon', models.FloatField(verbose_name='Min Longitude')),
                ('max_lon', models.FloatField(verbose_name='Max Longitude')),
                ('min_lat', models.FloatField(verbose_name='Min Latitude')),
                ('max_lat', models.FloatField(verbose_name='Max Latitude')),
                ('height', models.FloatField(default=0, verbose_name='Height offset')),
                ('scale', models.FloatField(default=1.0, verbose_name='Scale')),
                ('tileset_file', models.CharField(max_length=500, verbose_name='Tileset JSON path')),
                ('i3dm_file', models.CharField(max_length=500, verbose_name='I3DM binary path')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i3dm_tilesets', to='glb_app.glbmodel', verbose_name='Model gốc')),
            ],
            options={
                'verbose_name': 'I3DM Tileset',
                'verbose_name_plural': 'I3DM Tilesets',
                'db_table': 'i3dm_tileset',
                'ordering': ['-created_at'],
            },
        ),
    ]
