# Generated by Django 6.0.1 on 2026-01-12 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glb_app', '0001_initial'),
        ('i3dm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i3dmtileset',
            name='source_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i3dm_tilesets', to='glb_app.glbmodel', verbose_name='Model gốc'),
        ),
    ]
