# Generated by Django 5.2.5 on 2026-01-21 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiMoHinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_glb', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL GLB')),
                ('url_b3dm', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL B3DM')),
                ('parent', models.IntegerField(blank=True, null=True, verbose_name='ID cha')),
                ('loai_cap_nhat', models.CharField(max_length=50, verbose_name='Loại cập nhật')),
            ],
            options={
                'verbose_name': 'Loại mô hình',
                'verbose_name_plural': 'Loại mô hình',
                'db_table': 'tb_loai_mo_hinh',
            },
        ),
        migrations.CreateModel(
            name='ViTri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Vĩ độ')),
                ('lon', models.FloatField(verbose_name='Kinh độ')),
                ('height', models.FloatField(default=0.0, verbose_name='Độ cao')),
                ('heading', models.FloatField(default=0.0, verbose_name='Góc heading')),
                ('pitch', models.FloatField(default=0.0, verbose_name='Góc pitch')),
                ('roll', models.FloatField(default=0.0, verbose_name='Góc roll')),
                ('box', models.JSONField(blank=True, null=True, verbose_name='Bounding box')),
                ('scale', models.FloatField(default=1.0, verbose_name='Tỷ lệ scale')),
            ],
            options={
                'verbose_name': 'Vị trí',
                'verbose_name_plural': 'Vị trí',
                'db_table': 'tb_vi_tri',
            },
        ),
        migrations.CreateModel(
            name='MoHinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_canh', models.IntegerField(default=1, help_text='Mã số cảnh 3D', verbose_name='Mã cảnh')),
                ('ma_loai_mo_hinh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mo_hinhs', to='QLModel.loaimohinh', verbose_name='Loại mô hình')),
                ('ma_vi_tri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mo_hinhs', to='QLModel.vitri', verbose_name='Vị trí')),
            ],
            options={
                'verbose_name': 'Mô hình',
                'verbose_name_plural': 'Mô hình',
                'db_table': 'tb_mo_hinh',
            },
        ),
    ]
