# Generated by Django 5.2.5 on 2026-01-21 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_canh', models.IntegerField(help_text='Mã số cảnh 3D', unique=True, verbose_name='Mã cảnh')),
                ('ten_canh', models.CharField(max_length=100, verbose_name='Tên cảnh')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('lat', models.FloatField(help_text='Vị trí latitude của camera', verbose_name='Vĩ độ camera')),
                ('lon', models.FloatField(help_text='Vị trí longitude của camera', verbose_name='Kinh độ camera')),
                ('height', models.FloatField(default=1000.0, verbose_name='Độ cao camera')),
                ('heading', models.FloatField(default=0.0, verbose_name='Góc heading (độ)')),
                ('pitch', models.FloatField(default=-30.0, verbose_name='Góc pitch (độ)')),
                ('roll', models.FloatField(default=0.0, verbose_name='Góc roll (độ)')),
                ('url_terrain', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL Terrain/Tileset')),
            ],
            options={
                'verbose_name': 'Cảnh 3D',
                'verbose_name_plural': 'Các cảnh 3D',
                'db_table': 'canh',
                'ordering': ['ma_canh'],
            },
        ),
        migrations.AlterField(
            model_name='mohinh',
            name='ma_canh',
            field=models.ForeignKey(help_text='Cảnh mà loại mô hình này thuộc về', on_delete=django.db.models.deletion.CASCADE, related_name='loai_mo_hinhs', to='QLModel.canh', verbose_name='Cảnh'),
        ),
    ]
