# Generated by Django 5.2.5 on 2026-01-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QLModel', '0002_canh_alter_mohinh_ma_canh'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='canh',
            table='tb_canh',
        ),
    ]
