# Generated by Django 6.0.1 on 2026-01-27 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLModel', '0003_alter_canh_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai', models.CharField(max_length=100, verbose_name='Tên loài cây')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Chiều cao (m)')),
                ('duong_kinh', models.FloatField(blank=True, null=True, verbose_name='Đường kính thân (cm)')),
                ('tuoi', models.IntegerField(blank=True, null=True, verbose_name='Tuổi cây (năm)')),
                ('thuoc_tinh_khac', models.JSONField(blank=True, help_text='Thuộc tính mở rộng, động theo từng loại cây', null=True, verbose_name='Thuộc tính khác (JSON)')),
            ],
            options={
                'verbose_name': 'Cây',
                'verbose_name_plural': 'Cây',
                'db_table': 'tb_cay',
            },
        ),
        migrations.CreateModel(
            name='CongTrinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_cong_trinh', models.CharField(max_length=150, verbose_name='Tên công trình')),
                ('loai_cong_trinh', models.CharField(help_text='VD: NHA, CAU, CANG, TRAM', max_length=50, verbose_name='Loại công trình')),
                ('cap_bao_mat', models.SmallIntegerField(default=0, help_text='0: thường, 1: hạn chế, 2: mật', verbose_name='Cấp bảo mật')),
                ('thuoc_tinh_khac', models.JSONField(blank=True, null=True, verbose_name='Thuộc tính khác (JSON)')),
            ],
            options={
                'verbose_name': 'Công trình',
                'verbose_name_plural': 'Công trình',
                'db_table': 'tb_cong_trinh',
            },
        ),
        migrations.CreateModel(
            name='DTChuyenDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_DT', models.CharField(default='UNKNOWN', help_text='VD: TAU, XE, MAY_BAY, UAV', max_length=50, verbose_name='Loại đối tượng')),
                ('ten_doi_tuong', models.CharField(max_length=100, verbose_name='Tên đối tượng')),
                ('duong_chuyen_dong', models.TextField(help_text='Lưu polyline / GeoJSON / danh sách tọa độ', verbose_name='Đường chuyển động')),
                ('van_toc', models.FloatField(blank=True, null=True, verbose_name='Vận tốc')),
                ('thuoc_tinh_khac', models.JSONField(blank=True, null=True, verbose_name='Thuộc tính khác (JSON)')),
            ],
            options={
                'verbose_name': 'Đối tượng chuyển động',
                'verbose_name_plural': 'Đối tượng chuyển động',
                'db_table': 'tb_DT_chuyen_dong',
            },
        ),
        migrations.AddField(
            model_name='mohinh',
            name='hinh_anh',
            field=models.CharField(blank=True, help_text='VD: images/nha_01', max_length=255, null=True, verbose_name='Đường dẫn hình ảnh'),
        ),
        migrations.AddField(
            model_name='mohinh',
            name='loai_doi_tuong',
            field=models.SmallIntegerField(default=1, help_text='Ví dụ: 1: DOI TUONG CHUYEN DONG, 2: CAY, 3: CONG TRINH', verbose_name='Loại đối tượng'),
        ),
        migrations.AddField(
            model_name='mohinh',
            name='thoi_gian_cap_nhat',
            field=models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật'),
        ),
        migrations.AddField(
            model_name='mohinh',
            name='thoi_gian_tao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Thời gian tạo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mohinh',
            name='trang_thai',
            field=models.SmallIntegerField(default=1, help_text='1: Hoạt động, 0: Không hoạt động', verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='mohinh',
            name='ma_canh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mo_hinhs', to='QLModel.canh', verbose_name='Cảnh'),
        ),
        migrations.AlterField(
            model_name='mohinh',
            name='ma_loai_mo_hinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mo_hinhs', to='QLModel.loaimohinh', verbose_name='Loại mô hình'),
        ),
        migrations.AlterField(
            model_name='mohinh',
            name='ma_vi_tri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mo_hinhs', to='QLModel.vitri', verbose_name='Vị trí'),
        ),
    ]
