# Generated by Django 6.0.1 on 2026-01-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLModel', '0004_cay_congtrinh_dtchuyendong_mohinh_hinh_anh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaimohinh',
            name='ten_loai_mo_hinh',
            field=models.CharField(default='', help_text='Ví dụ: Cây cổ thụ, Nhà cao tầng, Xe tải, Tàu thuyền...', max_length=100, verbose_name='Tên loại mô hình'),
        ),
    ]
