# Generated by Django 5.1.7 on 2026-02-03 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLModel', '0005_loaimohinh_ten_loai_mo_hinh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mohinh',
            name='ma_canh',
            field=models.ForeignKey(db_column='ma_canh_id', on_delete=django.db.models.deletion.CASCADE, related_name='mo_hinhs', to='QLModel.canh', to_field='ma_canh', verbose_name='Cảnh'),
        ),
    ]
