# Generated by Django 6.0.1 on 2026-02-02 07:31

import django.db.models.deletion
import glb_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlbModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('glb_file', models.FileField(upload_to=glb_app.models.glb_upload_path)),
                ('lon', models.FloatField(default=0.0)),
                ('lat', models.FloatField(default=0.0)),
                ('height', models.FloatField(default=0.0)),
                ('scale', models.FloatField(default=1.0)),
                ('rotation_x', models.FloatField(default=0.0)),
                ('rotation_y', models.FloatField(default=0.0)),
                ('rotation_z', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Tileset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('folder', models.CharField(blank=True, max_length=500)),
                ('tileset_file', models.FileField(upload_to='tilesets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlbMesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesh_name', models.CharField(max_length=255)),
                ('vertex_data', models.TextField()),
                ('glb_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meshes', to='glb_app.glbmodel')),
            ],
        ),
    ]
