# Generated by Django 5.2.4 on 2025-08-06 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlbModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('glb_file', models.FileField(upload_to='glb_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlbMesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesh_name', models.CharField(max_length=255)),
                ('vertex_data', models.TextField()),
                ('glb_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meshes', to='glb_app.glbmodel')),
            ],
        ),
    ]
