# Generated by Django 5.2.4 on 2025-08-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glb_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glbmodel',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='glbmodel',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='glbmodel',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='glbmodel',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='glbmodel',
            name='scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='glbmodel',
            name='glb_file',
            field=models.FileField(upload_to='models/'),
        ),
        migrations.AlterField(
            model_name='glbmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
