# Generated by Django 5.2.4 on 2025-08-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glb_app', '0002_remove_glbmodel_uploaded_at_glbmodel_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glbmodel',
            name='rotation_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='glbmodel',
            name='rotation_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='glbmodel',
            name='rotation_z',
            field=models.FloatField(default=0.0),
        ),
    ]
