# Generated by Django 5.2.4 on 2025-08-06 09:42

import glb_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glb_app', '0003_glbmodel_rotation_x_glbmodel_rotation_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glbmodel',
            name='glb_file',
            field=models.FileField(upload_to=glb_app.models.glb_upload_path),
        ),
    ]
