# Generated by Django 5.2.5 on 2026-01-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glb_app', '0004_alter_glbmodel_glb_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tileset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('folder', models.CharField(blank=True, max_length=500)),
                ('tileset_file', models.FileField(upload_to='tilesets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
